import type { AnalysisProfile } from "./types";

export const FOOTWORK_PROFILE: AnalysisProfile = {
  id: "footwork_v1",
  scale_strategy: "torso_length",
  scale_scope: "sequence",
  dtw_features: [
    "left_ankle_x","left_ankle_y","right_ankle_x","right_ankle_y","foot_distance","pelvis_height",
  ],
  phases: {
    preparation: "В начале движения",
    stride: "В середине шага",
    landing: "В момент приземления",
    completion: "В завершении шага",
    overall: "На протяжении шага",
  },
  features: {
    foot_distance: spec(1, .12, .22, "torso_lengths", "расстояние между стопами",
      "{phase} расстояние между стопами больше, чем в эталоне, примерно на {magnitude}.",
      "{phase} расстояние между стопами меньше, чем в эталоне, примерно на {magnitude}."),
    left_ankle_x: spec(.85,.12,.22,"torso_lengths","положение левой стопы вперёд",
      "{phase} левая стопа ушла дальше вперёд относительно таза, чем в эталоне, примерно на {magnitude}.",
      "{phase} левая стопа осталась сзади относительно эталона, примерно на {magnitude}."),
    right_ankle_x: spec(.85,.12,.22,"torso_lengths","положение правой стопы вперёд",
      "{phase} правая стопа ушла дальше вперёд относительно таза, чем в эталоне, примерно на {magnitude}.",
      "{phase} правая стопа осталась сзади относительно эталона, примерно на {magnitude}."),
    pelvis_height: spec(.7,.08,.14,"torso_lengths","высота таза над стопами",
      "{phase} таз выше над стопами, чем в эталоне, примерно на {magnitude}. По сравнению с эталоном корпус сильнее выпрямляется.",
      "{phase} таз ниже над стопами, чем в эталоне, примерно на {magnitude}."),
    pelvis_bounce: {
      ...spec(.65,.035,.07,"torso_lengths","вертикальное колебание таза",
        "На протяжении шага высота таза гуляет сильнее, чем в эталоне (разброс больше примерно на {magnitude}).",
        "На протяжении шага высота таза держится ровнее, чем в эталоне."),
      source:"pelvis_height", reduce:"std",
    },
    left_knee_angle: spec(.6,12,22,"degrees","угол левого колена",
      "{phase} левое колено разогнуто сильнее, чем в эталоне, примерно на {magnitude}.",
      "{phase} левое колено согнуто сильнее, чем в эталоне, примерно на {magnitude}."),
    right_knee_angle: spec(.6,12,22,"degrees","угол правого колена",
      "{phase} правое колено разогнуто сильнее, чем в эталоне, примерно на {magnitude}.",
      "{phase} правое колено согнуто сильнее, чем в эталоне, примерно на {magnitude}."),
    torso_angle: spec(.75,8,15,"degrees","наклон корпуса",
      "{phase} корпус сильнее наклонён вперёд, чем в эталоне, примерно на {magnitude}.",
      "{phase} корпус сильнее отклонён назад, чем в эталоне, примерно на {magnitude}."),
    left_hip_angle: spec(.4,12,22,"degrees","угол в левом тазобедренном",
      "{phase} левое бедро разогнуто сильнее, чем в эталоне, примерно на {magnitude}.",
      "{phase} левое бедро согнуто сильнее, чем в эталоне, примерно на {magnitude}."),
    right_hip_angle: spec(.4,12,22,"degrees","угол в правом тазобедренном",
      "{phase} правое бедро разогнуто сильнее, чем в эталоне, примерно на {magnitude}.",
      "{phase} правое бедро согнуто сильнее, чем в эталоне, примерно на {magnitude}."),
    knee_over_foot_left: spec(.35,.1,.18,"torso_lengths","вынос левого колена относительно стопы",
      "{phase} левое колено заметно впереди стопы по сравнению с эталоном ({magnitude}).",
      "{phase} левое колено заметно сзади стопы по сравнению с эталоном ({magnitude})."),
    knee_over_foot_right: spec(.35,.1,.18,"torso_lengths","вынос правого колена относительно стопы",
      "{phase} правое колено заметно впереди стопы по сравнению с эталоном ({magnitude}).",
      "{phase} правое колено заметно сзади стопы по сравнению с эталоном ({magnitude})."),
    left_leg_extension: spec(.3,.08,.15,"torso_lengths","длина левой ноги от таза до стопы",
      "{phase} левая нога выпрямлена дальше, чем в эталоне, примерно на {magnitude}.",
      "{phase} левая нога собрана короче, чем в эталоне, примерно на {magnitude}."),
    right_leg_extension: spec(.3,.08,.15,"torso_lengths","длина правой ноги от таза до стопы",
      "{phase} правая нога выпрямлена дальше, чем в эталоне, примерно на {magnitude}.",
      "{phase} правая нога собрана короче, чем в эталоне, примерно на {magnitude}."),
    lateral_foot_distance: spec(.2,.12,.22,"torso_lengths","боковой разнос стоп",
      "{phase} стопы разведены в стороны сильнее, чем в эталоне, примерно на {magnitude}. Оценка глубины с одной камеры неточная.",
      "{phase} стопы уже по глубине кадра, чем в эталоне, примерно на {magnitude}. Оценка глубины с одной камеры неточная."),
    left_heel_x: spec(.15,.14,.26,"torso_lengths","положение левой пятки",
      "{phase} левая пятка дальше впереди, чем в эталоне, примерно на {magnitude}.",
      "{phase} левая пятка дальше сзади, чем в эталоне, примерно на {magnitude}."),
    right_heel_x: spec(.15,.14,.26,"torso_lengths","положение правой пятки",
      "{phase} правая пятка дальше впереди, чем в эталоне, примерно на {magnitude}.",
      "{phase} правая пятка дальше сзади, чем в эталоне, примерно на {magnitude}."),
    left_toe_x: spec(.15,.14,.26,"torso_lengths","положение носка левой стопы",
      "{phase} носок левой стопы дальше впереди, чем в эталоне, примерно на {magnitude}.",
      "{phase} носок левой стопы дальше сзади, чем в эталоне, примерно на {magnitude}."),
    right_toe_x: spec(.15,.14,.26,"torso_lengths","положение носка правой стопы",
      "{phase} носок правой стопы дальше впереди, чем в эталоне, примерно на {magnitude}.",
      "{phase} носок правой стопы дальше сзади, чем в эталоне, примерно на {magnitude}."),
  },
};

function spec(weight:number, warning:number, major:number, unit:string, label:string, greater:string, less:string) {
  return { weight, warning_threshold:warning, major_threshold:major, unit, label, greater, less, reduce:"mean" as const };
}
